### PR TITLE
Add pages on how to contribute a new data source

### PR DESCRIPTION
**Pull request by colleenXu**
Will include pages on 3 different methods:
* biothings SDK (done)
* plover (in progress)
* plater/automat (in progress)

each will probably have linkouts to team/tool-specific info

### CODE REVIEW

**Comment by colleenXu** [comment]
Convo from Slack:

Amy Glen (Expander Agent):  

>  added initial version for Plover; it links to some placeholder sections in our repo, will get those updated soon… https://github.com/NCATSTranslator/TranslatorTechnicalDocumentation/blob/data-contributor-guide/docs/data-contributor-guide/plover.md

Evan Morris:

> Plater needed quite a bit of updating, and we are very close to releasing a new version that would affect the docs as well, but I will get this done within the next week.

**Comment by RichardBruskiewich** [comment]
Hi @colleenXu  (cc: @andrewsu), I guess we were starting work on this objective concurrently. There's now a draft landing page: https://github.com/NCATSTranslator/TranslatorTechnicalDocumentation/blob/master/docs/development-guide/tutorials/component_builders_roadmap.md.  Please take a look and see how to cross-link the two

**Comment by colleenXu** [comment]
## Update

Kelyne asked me to resolve the issue Richard brought up above (cross-linking). So I did this with my recent commits. 

There are some pending updates to pages:
* @amykglen Is your page ready? 
* @EvanDietzMorris Your page isn't filled out yet. 

I imagine if this PR ends up merged before your updates are done, you'll have to make a new PR.

**Comment by EvanDietzMorris** [comment]
Sorry, I am still not finished with releasing our new Plater version which will have substantial changes to the Plater docs, so this got delayed. I should be able to get something in tomorrow, but if you want you could go ahead and merge this with a placeholder for Plater and I will make a new PR.

**Comment by colleenXu** [comment]
I dunno how urgent this is either :P, just wanted to check in on the status of things! 

I imagine if you can get something done this week, that'd be great.

**Review by RichardBruskiewich — APPROVED** [review]

**Comment by RichardBruskiewich** [comment]
Hi @colleenXu , thanks for the contributions. I tweaked the commit a tiny bit - page locations, links, merging landing page (into 'Tutorials") but left the contributed markdown files intact. Merged the result.  Content now live at https://ncatstranslator.github.io/TranslatorTechnicalDocumentation/development-guide/tutorials/component_builders_roadmap/

**Pull request merged**
